# Generated by Django 5.2.1 on 2025-05-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solarstation_energydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energydata',
            options={'permissions': [('can_view_analytics', 'Can view energy analytics')]},
        ),
        migrations.AlterModelOptions(
            name='solarstation',
            options={'permissions': [('can_manage_stations', 'Can manage solar stations')]},
        ),
    ]
