# Generated by Django 5.2.1 on 2025-06-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_energydata_options_alter_solarstation_options'),
    ]

    operations = [
    ]
