# Generated by Django 5.2.1 on 2025-06-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_energydata_options_alter_solarstation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название системы')),
                ('location', models.TextField(verbose_name='Местоположение')),
                ('system_type', models.CharField(choices=[('Сетевая', 'Сетевая'), ('Гибридная', 'Гибридная'), ('Автономная', 'Автономная')], max_length=50, verbose_name='Тип системы')),
                ('installed_power', models.FloatField(verbose_name='Установленная мощность (кВт)')),
                ('installation_date', models.DateField(verbose_name='Дата установки')),
                ('panel_count', models.PositiveIntegerField(verbose_name='Количество панелей')),
                ('panel_type', models.CharField(choices=[('Монокристалл', 'Монокристалл'), ('Поликристалл', 'Поликристалл'), ('Тонкая плёнка', 'Тонкая плёнка')], max_length=50, verbose_name='Тип панелей')),
                ('panel_power', models.FloatField(verbose_name='Мощность одной панели (Вт)')),
                ('panel_manufacturer', models.CharField(max_length=255, verbose_name='Производитель панелей')),
                ('tilt_angle', models.FloatField(verbose_name='Угол наклона')),
                ('orientation', models.CharField(max_length=50, verbose_name='Ориентация')),
                ('inverter_type', models.CharField(choices=[('Сетевой', 'Сетевой'), ('Гибридный', 'Гибридный'), ('Автономный', 'Автономный')], max_length=50, verbose_name='Тип инвертора')),
                ('inverter_power', models.FloatField(verbose_name='Мощность инвертора (кВт)')),
                ('inverter_manufacturer', models.CharField(max_length=255, verbose_name='Производитель инвертора')),
                ('controller_type', models.CharField(choices=[('PWM', 'PWM'), ('MPPT', 'MPPT')], max_length=50, verbose_name='Тип контроллера')),
                ('battery_type', models.CharField(choices=[('Свинцово-кислотные', 'Свинцово-кислотные'), ('AGM', 'AGM'), ('Гелевые', 'Гелевые'), ('Литиевые', 'Литиевые')], max_length=50, verbose_name='Тип аккумуляторов')),
                ('battery_count', models.PositiveIntegerField(verbose_name='Количество аккумуляторов')),
                ('battery_capacity_single', models.FloatField(verbose_name='Емкость одного аккумулятора (кВт·ч)')),
                ('battery_voltage', models.CharField(choices=[('12 В', '12 В'), ('24 В', '24 В'), ('48 В', '48 В')], max_length=10, verbose_name='Напряжение системы')),
                ('battery_manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
    ]
