# Generated by Django 5.2.1 on 2025-06-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последней проверки'),
        ),
    ]
