# Generated by Django 5.2.1 on 2025-06-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_station_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='force_attention_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принудительный статус до'),
        ),
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('normal', 'Норма'), ('attention', 'Требует внимания')], default='normal', max_length=20, verbose_name='Состояние'),
        ),
    ]
